name = "Patchouli (Fabric)"
filename = "Patchouli-1.18.1-65-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/726/Patchouli-1.18.1-65-FABRIC.jar"
hash-format = "sha1"
hash = "8394d0e39f847d2ca548830ffd2f67684a7b9f1f"

[update]
[update.curseforge]
file-id = 3630726
project-id = 393236
