name = "ServerCore"
filename = "servercore-1.2.8-1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/4WWQxlQP/versions/1.2.8-1.18.1/servercore-1.2.8-1.18.1.jar"
hash-format = "sha1"
hash = "bc756dcf90e45b40b633d19789c5c8028322906d"

[update]
[update.modrinth]
mod-id = "4WWQxlQP"
version = "IOuEmJ7r"
